### PR TITLE
Fix for displaying sub-pages as dialogs

### PR DESCRIPTION
**Pull request by adammessinger**
Also cleaned up some white space for consistency with rest of source. Addresses issue #1.

### CODE REVIEW

**Comment by ToddThomson** [comment]
When jQM moves to release 1.1, I will review the changes made with respect to data-rel="dialog". Thank-you for your code submission!

**Comment by adammessinger** [comment]
Sounds good, Todd. Thanks.

**Comment by michelpa** [comment]
Hello, maybe you can merge this PR as it seems to be OK with 1.1.0?

**Comment by ToddThomson** [comment]
Please note that I've noticed a minor issue with subpages and fixed toolbars (headers) in jQM 1.1.0.

**Comment by ToddThomson** [comment]
I've rewritten the subpage widget ( the 1.0 ver was a quick hack, but it did work ). Please test out the new version and I'll update the version to 1.1 from 1.1RC in a week if there are no new issues found.

**Pull request merged**
